export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const LOGIN            = 'LOGIN';
export const REGISTER         = 'REGISTER';
export const APP_LOAD         = 'APP_LOAD';
export const SETTINGS_SAVED   = 'SETTINGS_SAVED';
export const LOGOUT           = 'LOGOUT';
export const ARTICLE_DETAIL_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_COMMENT_LOADED = 'ARTICLE_COMMENT_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const DELETE_ARTICLE  = 'DELETE_ARTICLE';
export const ADD_COMMENT     = 'ADD_COMMENT';
export const DELETE_COMMENT  = 'DELETE_COMMENT';
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';
export const PROFILE_FAVORITES_PAGE_LOADED = 'PROFILE_FAVORITES_PAGE_LOADED';
export const PROFILE_FAVORITES_PAGE_UNLOADED = 'PROFILE_FAVORITES_PAGE_UNLOADED';
export const FOLLOW_USER     = 'FOLLOW_USER';
export const UNFOLLOW_USER   = 'UNFOLLOW_USER';
export const CHANGE_TAB      = 'CHANGE_TAB';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
export const SET_PAGE        = 'SET_PAGE';
export const ARTICLE_CREATED = 'ARTICLE_CREATED';
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';





































